name: Publica imágenes en el GitHub Package Registry
on: push
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:

    - name: Check out files
      uses: actions/checkout@master

    - name: Publica imagen al GPR
      uses: JJ/gpr-docker-publish@master
      with:
        IMAGE_NAME: 'hola-mundo-alpine'
        TAG: 'latest'
        DOCKERFILE_PATH: 'alpine/Dockerfile'
        BUILD_CONTEXT: 'alpine/'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publica imagen al GPR
      uses: JJ/gpr-docker-publish@master
      with:
        IMAGE_NAME: 'hola-mundo-ubuntu'
        TAG: 'latest'
        DOCKERFILE_PATH: 'ubuntu/Dockerfile'
        BUILD_CONTEXT: 'ubuntu/'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publica imagen al GPR
      uses: JJ/gpr-docker-publish@master
      with:
        IMAGE_NAME: 'hola-mundo-minideb'
        TAG: 'latest'
        DOCKERFILE_PATH: 'minideb/Dockerfile'
        BUILD_CONTEXT: 'minideb/'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
